# plugin.yml
name: DynamicShop
version: 2.3.0
main: org.minecraftsmp.dynamicshop.DynamicShop
api-version: 1.20
author: selfservice0
description: A dynamic economy shop with player-interactive GUI
website: https://minecraftsmp.org

depend: [Vault, ProtocolLib]
softdepend: [PlaceholderAPI, ItemsAdder]

commands:
  shop:
    description: Open the dynamic shop GUI
    usage: /shop [sell <price>]
    aliases: [ dshop, market ]
    permission: dynamicshop.use
  shopadmin:
    description: Admin commands for managing the shop
    usage: /shopadmin <reload|save|reset|setstock|info|resetshortage>
    aliases: [dsa, shopadm]
    permission: dynamicshop.admin

permissions:
  dynamicshop.use:
    description: Allows using the shop
    default: true
  dynamicshop.admin:
    description: Allows managing the shop
    default: op
  dynamicshop.bypass.stock:
    description: Allows buying items even when out of stock (if restricted)
    default: op
  dynamicshop.bypass.cooldown:
    description: Allows bypassing the transaction cooldown
    default: op
  dynamicshop.playershop.sell:
    description: Allows listing items in player shops
    default: true