  function renderActions(){
    currentContent().innerHTML=`<div class="admin-section-intro"><div><h2>Shop actions</h2><p>Maintenance controls for your server.</p></div></div><div class="admin-action-grid"><section class="admin-config-card"><h3>Website files</h3><p id="websiteFileStatus" role="status">Checking installed website files…</p><p>Install the website bundled with this plugin. Existing files are backed up in <code>web-backups/</code>. Shop data and appearance settings are kept.</p><button class="primary" id="updateWebsiteFiles">Update website files</button><button class="secondary" id="checkWebsiteFiles">Check again</button></section><section class="admin-config-card"><h3>Reset shortage data</h3><p>Clear accumulated shortage hours for all items.</p><button class="admin-danger" id="resetAllAdminShortage">Reset all shortage data</button></section><section class="admin-config-card"><h3>Set stock in bulk</h3><p>Set the same stock level for all standard shop items.</p>${input('adminAllStock','Stock amount',0,'type="number" step="1"')}<button class="secondary" id="setAllAdminStock">Set all stock</button></section><section class="admin-config-card"><h3>Reload plugin</h3><p>Reload configuration files, like <code>/shopadmin reload</code>.</p><button class="secondary" id="reloadAdminPlugin">Reload plugin</button></section></div>`;
    async function check(){try{const status=await api('/api/admin/website-files',{auth:true});if($('websiteFileStatus'))$('websiteFileStatus').textContent=status.needsUpdate?'Update available: '+status.outdatedFiles.join(', '):'Website files are up to date with plugin '+status.version+'.'}catch(error){if($('websiteFileStatus'))$('websiteFileStatus').textContent=error.message}}
    $('checkWebsiteFiles').onclick=check;check();
    $('updateWebsiteFiles').onclick=()=>confirmAction('Update website files?','Back up the current web files, then replace them with the files bundled with this plugin. Custom HTML, CSS, and JavaScript edits will be replaced; the backup keeps a copy.',async()=>{const result=await api('/api/admin/website-files/update',{auth:true,method:'POST',body:{}});setTimeout(()=>location.reload(),3500);return 'Website updated. Backup: '+result.backup});
    $('resetAllAdminShortage').onclick=()=>confirmAction('Reset all shortage data?','Clear every item shortage counter on the server.',()=>api('/api/admin/resetshortage',{auth:true,method:'POST',body:{}}));
    $('setAllAdminStock').onclick=()=>{const value=Number($('adminAllStock').value);if(!$('adminAllStock').value.trim()||!Number.isSafeInteger(value)){notify('Enter a whole stock amount');return}const invalid=items.find(i=>i.maxStockStorage!=null&&value>i.maxStockStorage);if(invalid){notify('Exceeds the storage limit for '+invalid.name);return}confirmAction('Set all stock to '+value+'?',items.length+' standard shop items will be updated.',()=>api('/api/admin/items/bulk',{auth:true,method:'POST',body:{items:items.map(i=>i.id),updates:{stock:value}}}))};
    $('reloadAdminPlugin').onclick=()=>confirmAction('Reload plugin?','Reload the server configuration from disk.',()=>api('/api/admin/reload',{auth:true,method:'POST',body:{}}));
  }
  function renderAudit(){currentContent().innerHTML=`<div class="admin-section-intro"><div><h2>Admin change log</h2><p>Changes recorded by your Minecraft server.</p></div><button class="secondary" id="refreshAdminAudit">Refresh</button></div><div class="admin-audit-list">${state.audit.map(entry=>`<article><span class="admin-audit-symbol">${icon('edit')}</span><div><strong>${esc(entry.action)} <span>· ${esc(entry.target)}</span></strong><p>${esc(entry.details)}</p><small>${esc(entry.user)} · ${esc(new Date(entry.timestamp).toLocaleString())}</small></div></article>`).join('')||'<div class="admin-empty">No changes recorded.</div>'}</div>`;$('refreshAdminAudit').onclick=async()=>{try{state.audit=await api('/api/admin/audit',{auth:true});renderAudit()}catch(error){notify(error.message)}}}
