  function renderAppearance(){
    themeFontOptions.forEach(([key])=>ensureThemeFont(key));
    const draft={...appearance,layoutStyles:{...appearance.layoutStyles}};
    const choices=(key,label,options)=>`<fieldset class="appearance-choices"><legend>${label}</legend><div>${options.map(([value,name])=>`<button type="button" data-choice="${key}" data-value="${value}" aria-pressed="${String(draft[key])===String(value)}">${name}</button>`).join('')}</div></fieldset>`;
    const colorField=(key,label)=>`<div class="appearance-color-field"><label for="theme_${key}">${label}</label><div><input type="color" data-color-picker="${key}" value="${draft[key]}" aria-label="${label} picker"><input id="theme_${key}" data-color-text="${key}" value="${draft[key]}" aria-label="${label} hex" pattern="#[0-9a-fA-F]{6}" maxlength="7" spellcheck="false" required></div></div>`;
    currentContent().innerHTML=`<div class="admin-section-intro"><div><h2>Make this market yours</h2><p>Set the colors, typography, and layout players see throughout your shop.</p></div></div>
    <form id="appearanceForm"><div class="appearance-layout"><div class="appearance-controls">
      <section class="admin-config-card"><h3>Website design</h3><p>Six different layouts. The same shop, watchlist, and admin tools.</p><div class="design-picker" role="group" aria-label="Website design"><button type="button" data-design="classic" aria-pressed="${draft.design==='classic'}"><span class="design-thumbnail design-classic"><i></i><b></b><em></em><em></em><em></em></span><strong>Classic</strong><small>Sidebar navigation, a colorful welcome panel, and item cards.</small></button><button type="button" data-design="market" aria-pressed="${draft.design==='market'}"><span class="design-thumbnail design-market"><i></i><b></b><em></em><em></em><em></em></span><strong>Market Hall</strong><small>A wide storefront, top navigation, and a compact trading list.</small></button><button type="button" data-design="inventory" aria-pressed="${draft.design==='inventory'}"><span class="design-thumbnail design-inventory"><i></i><b></b><em></em><em></em><em></em></span><strong>Inventory</strong><small>A game-inspired shop with item slots, gold highlights, and a compact toolbar.</small></button><button type="button" data-design="nova" aria-pressed="${draft.design==='nova'}"><span class="design-thumbnail design-nova"><i></i><b></b><em></em><em></em><em></em></span><strong>Nova</strong><small>A modern interactive storefront with quick search, featured discoveries, and fluid cards.</small></button><button type="button" data-design="chest" aria-pressed="${draft.design==='chest'}"><span class="design-thumbnail design-chest"><i></i><b></b><em></em><em></em><em></em></span><strong>Chest GUI</strong><small>The imported Minecraft storefront: stone panels, beveled slots, pixel headings, and a category rail.</small></button><button type="button" data-design="dsx" aria-pressed="${draft.design==='dsx'}"><span class="design-thumbnail design-dsx"><i></i><b></b><em></em><em></em><em></em></span><strong>DSX Exchange</strong><small>A trading terminal with a quote board, amber and cyan prices, and a market ticker.</small></button></div><p class="appearance-hint">Each design remembers its own colors and styling. These preferences are shared by everyone on this server website.</p></section>
      <section class="admin-config-card"><h3>Branding</h3>${input('appearanceTitle','Shop title',draft.title,'required maxlength="40" autocomplete="off"')}${input('appearanceSubtitle','Sidebar subtitle',draft.subtitle,'maxlength="60" autocomplete="off"','Optional. Leave empty to show only the title.')}</section>
      <section class="admin-config-card"><h3>Home button</h3><p>Redirect players to your server website when they click Home.</p>${toggle('appearanceHomeEnabled','Show Home button',draft.homeEnabled,'Display it in the top bar on every page.')}<div class="appearance-home-fields">${input('appearanceHomeLabel','Button label',draft.homeLabel,'maxlength="32" autocomplete="off"')}${input('appearanceHomeUrl','Website URL',draft.homeUrl,'type="url" required maxlength="2048" inputmode="url" spellcheck="false" placeholder="https://yourserver.com"')}<p class="appearance-hint">Enter the full website address, starting with https:// or http://. Home redirects there in the current tab unless you enable a new tab below.</p>${toggle('appearanceHomeNewTab','Open in a new tab',draft.homeNewTab)}</div><div class="appearance-home-preview" id="appearanceHomePreview">${icon('home')}<span id="appearanceHomePreviewLabel"></span><small id="appearanceHomePreviewUrl"></small></div></section>
      <section class="admin-config-card"><h3>Colors & surfaces</h3>${choices('mode','Base theme',[['dark','Dark'],['light','Light'],['custom','Custom']])}<p class="appearance-hint">Dark and Light reset the three surface colors. Custom lets you choose them separately.</p><h4 class="appearance-color-heading">Color palettes</h4><p class="appearance-hint">Apply four coordinated colors to this design, then fine-tune them below.</p><div class="theme-palettes" role="group" aria-label="Color palettes">${themePalettes.map(p=>`<button type="button" data-theme-palette="${p.id}" aria-pressed="false" aria-label="${p.name} palette"><span class="palette-swatches" aria-hidden="true">${paletteKeys.map(key=>`<i style="background:${p[key]}"></i>`).join('')}</span><strong>${p.name}</strong><small>${p.tone}</small></button>`).join('')}</div><h4 class="appearance-color-heading">Accent presets</h4><div class="theme-presets" role="group" aria-label="Accent presets">${themePresets.map(([name,color])=>`<button type="button" data-theme-color="${color}" aria-pressed="${draft.accent===color}" style="--swatch:${color}"><span></span>${name}</button>`).join('')}</div><div class="appearance-colors">${colorField('accent','Accent color')}${colorField('background','Page background')}${colorField('panel','Cards & panels')}${colorField('sidebar','Sidebar background')}</div><p class="appearance-hint">Text colors adjust automatically to keep your chosen surfaces readable.</p></section>
      <section class="admin-config-card"><h3>Typography & layout</h3><fieldset class="appearance-choices appearance-font-choices"><legend>Font style</legend><div>${themeFontOptions.map(([key,name,family])=>`<button type="button" data-choice="font" data-value="${key}" aria-label="${name} font" aria-pressed="${draft.font===key}"><span class="font-option-label">${name}</span><span class="font-option-sample" style="font-family:${esc(themeFonts[key])}">Diamond · $100</span><small>${family}</small></button>`).join('')}</div><p class="appearance-hint">Choose a lettering style, then save to apply it. Web fonts use a system fallback if unavailable.</p></fieldset>${choices('radius','Corner style',[[0,'Square'],[10,'Soft'],[20,'Rounded']])}${choices('density','Catalog spacing',[['comfortable','Comfortable'],['compact','Compact']])}${toggle('themeHero','Show welcome banner',draft.hero,'Display the large welcome banner above the catalog.')}${toggle('themeMotion','Animated effects',draft.motion,'Floating artwork and hover movement. Reduced-motion browser preferences are always respected.')}</section>
    </div><section class="appearance-preview-wrap"><div class="eyebrow">LIVE PREVIEW</div><div class="appearance-sample" id="appearanceSample"><div class="appearance-sample-brand"><strong id="appearanceSampleTitle"></strong><small id="appearanceSampleSubtitle"></small></div><div class="appearance-sample-nav">${icon('grid')} Item catalog <span>${items.length}</span></div><div class="appearance-mini-hero" id="appearanceSampleHero">Good finds. <strong>Better trades.</strong></div><div class="appearance-sample-item">${thumb('diamond')}<div><small>YOUR MARKETPLACE</small><h3>Diamond</h3><p>Available to trade</p></div></div><div class="appearance-sample-prices"><span>Buy price<strong>$100.00</strong></span><span>Sell price<strong>$70.00</strong></span></div><div class="appearance-sample-button">Explore the catalog <span>↗</span></div></div><p>Save to apply your theme for everyone visiting your server website. Only administrators can change these settings.</p><div class="appearance-preview-actions"><button class="primary" type="submit">Save appearance</button><button class="secondary" type="button" id="discardAppearance">Discard unsaved changes</button><button class="admin-text-button" type="button" id="resetAppearance">Reset to defaults</button></div><p id="appearanceStatus" role="status">Saved appearance applies to every visitor and survives server restarts.</p><p class="admin-form-error" id="appearanceError" role="alert"></p></section></div></form>`;
    function updateSample(){
      $('appearanceSampleTitle').textContent=draft.title||appearanceDefaults.title;
      $('appearanceSampleSubtitle').textContent=draft.subtitle;
      $('appearanceSampleHero').hidden=!draft.hero;
      $('appearanceHomePreview').hidden=!draft.homeEnabled;$('appearanceHomePreviewLabel').textContent=draft.homeLabel||'Home';$('appearanceHomePreviewUrl').textContent=(draft.homeUrl||'Choose a destination')+(draft.homeNewTab?' ↗':'');
      for(const id of ['appearanceHomeLabel','appearanceHomeUrl','appearanceHomeNewTab'])$(id).disabled=!draft.homeEnabled;
      setTheme($('appearanceSample'),draft);
      $('appearanceSample').dataset.design=draft.design;
      document.querySelectorAll('button[data-design]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.design===draft.design)));
      $('appearanceSample').dataset.motion=String(draft.motion);
      document.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===String(draft[b.dataset.choice]))));
      document.querySelectorAll('[data-theme-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeColor===draft.accent.toLowerCase())));
      document.querySelectorAll('[data-theme-palette]').forEach(b=>{const palette=themePalettes.find(p=>p.id===b.dataset.themePalette);b.setAttribute('aria-pressed',String(paletteKeys.every(key=>draft[key].toLowerCase()===palette[key])))});
    }
    function syncFields(){
      $('appearanceTitle').value=draft.title;$('appearanceSubtitle').value=draft.subtitle;
      $('themeHero').checked=draft.hero;$('themeMotion').checked=draft.motion;
      $('appearanceHomeEnabled').checked=draft.homeEnabled;$('appearanceHomeLabel').value=draft.homeLabel;$('appearanceHomeUrl').value=draft.homeUrl;$('appearanceHomeNewTab').checked=draft.homeNewTab;
      document.querySelectorAll('[data-color-text]').forEach(f=>f.value=draft[f.dataset.colorText]);
      document.querySelectorAll('[data-color-picker]').forEach(f=>f.value=draft[f.dataset.colorPicker]);updateSample();
    }
    $('appearanceTitle').oninput=e=>{draft.title=e.target.value;updateSample()};$('appearanceSubtitle').oninput=e=>{draft.subtitle=e.target.value;updateSample()};
    document.querySelectorAll('button[data-design]').forEach(b=>b.onclick=()=>{if(b.dataset.design===draft.design)return;draft.layoutStyles[draft.design]=layoutStyle(draft);draft.design=b.dataset.design;const saved=draft.layoutStyles[draft.design];const candidate={...appearanceDefaults,...saved};Object.assign(draft,layoutStyle(saved&&validAppearance(candidate)?candidate:layoutDefaults[draft.design]));syncFields();$('appearanceStatus').textContent='Design selected. Save appearance to switch the website.'});
    $('appearanceHomeEnabled').onchange=e=>{draft.homeEnabled=e.target.checked;updateSample()};$('appearanceHomeLabel').oninput=e=>{draft.homeLabel=e.target.value;updateSample()};$('appearanceHomeUrl').oninput=e=>{draft.homeUrl=e.target.value;updateSample()};$('appearanceHomeNewTab').onchange=e=>{draft.homeNewTab=e.target.checked;updateSample()};
    document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const key=b.dataset.choice;draft[key]=key==='radius'?Number(b.dataset.value):b.dataset.value;if(key==='mode'&&themeSurfaces[draft.mode])Object.assign(draft,themeSurfaces[draft.mode]);syncFields();$('appearanceStatus').textContent='Unsaved changes · save to apply.'});
    function changeColor(key,value){if(!/^#[0-9a-f]{6}$/i.test(value))return;draft[key]=value.toLowerCase();if(key!=='accent')draft.mode='custom';document.querySelector(`[data-color-picker="${key}"]`).value=draft[key];document.querySelector(`[data-color-text="${key}"]`).value=draft[key];updateSample();$('appearanceStatus').textContent='Unsaved changes · save to apply.'}
    document.querySelectorAll('[data-color-text]').forEach(f=>f.oninput=()=>changeColor(f.dataset.colorText,f.value));
    document.querySelectorAll('[data-color-picker]').forEach(f=>f.oninput=()=>changeColor(f.dataset.colorPicker,f.value));
    document.querySelectorAll('[data-theme-color]').forEach(b=>b.onclick=()=>changeColor('accent',b.dataset.themeColor));
    document.querySelectorAll('[data-theme-palette]').forEach(b=>b.onclick=()=>{const palette=themePalettes.find(p=>p.id===b.dataset.themePalette);for(const key of paletteKeys)draft[key]=palette[key];draft.mode='custom';syncFields();$('appearanceStatus').textContent=palette.name+' palette selected · save to apply.'});
    $('themeHero').onchange=e=>{draft.hero=e.target.checked;updateSample()};$('themeMotion').onchange=e=>{draft.motion=e.target.checked;updateSample()};
    $('discardAppearance').onclick=renderAppearance;
    $('resetAppearance').onclick=()=>{Object.assign(draft,appearanceDefaults);syncFields();$('appearanceStatus').textContent='Defaults selected. Save appearance to apply them.'};
    $('appearanceForm').oninput=()=>{$('appearanceStatus').textContent='Unsaved changes · save to apply.';$('appearanceError').textContent=''};
    $('appearanceForm').onsubmit=async event=>{
      event.preventDefault();const next={...draft,title:draft.title.trim(),subtitle:draft.subtitle.trim(),homeLabel:draft.homeLabel.trim(),homeUrl:draft.homeUrl.trim()};
      if(!validHomeSettings(next)){$('appearanceError').textContent='Enter a Home button label and a full website URL starting with https:// or http://.';return}
      if(!validAppearance(next)){$('appearanceError').textContent='Check the shop title and theme values. Colors must use six-digit hex codes.';return}
      next.layoutStyles={};for(const id of ['classic','market','inventory','nova','chest','dsx']){const saved=draft.layoutStyles[id];if(saved&&validAppearance({...appearanceDefaults,...saved}))next.layoutStyles[id]=layoutStyle(saved)}next.layoutStyles[next.design]=layoutStyle(next);
      const submit=$('appearanceForm').querySelector('[type=submit]');submit.disabled=true;
      try{appearance=await api('/api/admin/appearance',{auth:true,method:'POST',body:next});applyAppearance(appearance);$('appearanceError').textContent='';$('appearanceStatus').textContent='Appearance saved for all visitors.';notify('Website appearance saved')}
      catch(error){$('appearanceError').textContent=error.message}
      finally{submit.disabled=false}

    };
    updateSample();
  }
