// Nova's interactions share the catalog, drawer, and watchlist used by every design.
(() => {
  const active=()=>document.documentElement.dataset.design==='nova';
  const motion=()=>active()&&document.documentElement.dataset.themeMotion!=='false'&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
  const command=document.createElement('button');command.type='button';command.className='nova-command nova-only';command.innerHTML=icon('search')+'<span>Quick find</span><kbd>Ctrl K</kbd>';document.querySelector('.topbar-right').prepend(command);
  const spotlight=document.createElement('section');spotlight.className='nova-spotlight nova-only';spotlight.setAttribute('aria-label','Featured discoveries');
  spotlight.innerHTML='<div class="nova-spotlight-label"><span>THE DISCOVERY DECK</span><span id="novaFeaturedIndex"></span></div><button type="button" id="novaFeaturedOpen" class="nova-featured-open"><div id="novaFeaturedArt"></div><div class="nova-featured-info"><span id="novaFeaturedCategory"></span><h2 id="novaFeaturedName"></h2><div><span>BUY PRICE<strong id="novaFeaturedPrice"></strong></span><span class="nova-featured-arrow">↗</span></div></div></button><div class="nova-featured-controls"><span>Pick your next upgrade</span><button type="button" id="novaPrevious" aria-label="Previous featured item">←</button><button type="button" id="novaNext" aria-label="Next featured item">→</button></div>';
  document.querySelector('.hero').append(spotlight);
  let featured=[];let featuredIndex=0;
  function updateFeatured(){featured=items.filter(i=>i.buy!==null).slice(0,5).map(i=>i.id);spotlight.hidden=!featured.length;featuredIndex=featured.length?featuredIndex%featured.length:0;const item=items.find(i=>i.id===featured[featuredIndex]);if(!item)return;$('novaFeaturedArt').innerHTML=art(item.id);$('novaFeaturedCategory').textContent=item.category;$('novaFeaturedName').textContent=item.name;$('novaFeaturedPrice').textContent=money(item.buy);$('novaFeaturedIndex').textContent=String(featuredIndex+1).padStart(2,'0')+' / '+featured.length;$('novaFeaturedOpen').setAttribute('aria-label','Explore '+item.name)}
  $('novaFeaturedOpen').onclick=()=>{if(featured.length)openItem(featured[featuredIndex])};
  window.addEventListener('catalog-updated',updateFeatured);
  $('novaPrevious').onclick=()=>{if(!featured.length)return;featuredIndex=(featuredIndex+featured.length-1)%featured.length;updateFeatured()};$('novaNext').onclick=()=>{if(!featured.length)return;featuredIndex=(featuredIndex+1)%featured.length;updateFeatured()};updateFeatured();
  const viewbar=document.createElement('div');viewbar.className='nova-viewbar nova-only';
  viewbar.innerHTML='<div class="nova-view-options" role="group" aria-label="Catalog layout"><button type="button" data-nova-view="grid" aria-pressed="true">'+icon('grid')+' Grid</button><button type="button" data-nova-view="list" aria-pressed="false">'+icon('activity')+' List</button></div><button type="button" id="novaDiscover">Discover an item <span>↗</span></button>';
  $('itemGrid').before(viewbar);
  document.querySelectorAll('[data-nova-view]').forEach(b=>b.onclick=()=>{document.documentElement.dataset.novaView=b.dataset.novaView;document.querySelectorAll('[data-nova-view]').forEach(button=>button.setAttribute('aria-pressed',String(button===b)))});
  $('novaDiscover').onclick=()=>{const visible=Array.from($('itemGrid').querySelectorAll('[data-open]')).map(b=>items.find(i=>i.id===b.dataset.open)).filter(i=>i&&!i.disabled);if(!visible.length){notify('No available items in this view');return}openItem(visible[Math.floor(Math.random()*visible.length)].id)};
  const finder=document.createElement('dialog');finder.id='novaFinder';finder.setAttribute('aria-labelledby','novaFinderTitle');
  finder.innerHTML='<div class="nova-finder-heading"><div><span>LESS SCROLLING. MORE DISCOVERY.</span><h2 id="novaFinderTitle">Find your next item</h2></div><button type="button" class="icon-button" id="novaCloseFinder" aria-label="Close quick find">✕</button></div><label class="nova-finder-input">'+icon('search')+'<input id="novaFindInput" type="search" placeholder="Try diamond, tools, or watering can…" aria-label="Quick find items" autocomplete="off"></label><p id="novaFindCount" role="status"></p><div id="novaFindResults"></div><div class="nova-finder-hint"><span>↑ ↓ to move · Enter to explore</span><span>Esc to close</span></div>';
  document.body.append(finder);
  function findItems(){const query=$('novaFindInput').value.trim().toLowerCase();const matches=items.filter(i=>(i.name+' '+i.category).toLowerCase().includes(query));const shown=matches.slice(0,8);$('novaFindCount').textContent=query?matches.length+' matching items'+(matches.length>8?' · showing the first 8':''):'Start typing to search all '+items.length+' items';$('novaFindResults').innerHTML=shown.map(i=>'<button class="nova-find-result" type="button" data-find-item="'+escapeText(i.id)+'">'+art(i.id)+'<span><strong>'+escapeText(i.name)+'</strong><small>'+escapeText(i.category)+'</small></span><span>'+ (i.disabled?'Unavailable':money(i.buy))+'</span><span>↗</span></button>').join('')||'<div class="nova-find-empty">No matches. Try a different item name or category.</div>'}
  function showFinder(){if(!active()||document.querySelector('dialog[open]'))return;finder.showModal();document.body.style.overflow='hidden';$('novaFindInput').value='';findItems();$('novaFindInput').focus()}
  command.onclick=showFinder;$('novaCloseFinder').onclick=()=>finder.close();finder.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.style.overflow=''});$('novaFindInput').oninput=findItems;
  $('novaFindResults').onclick=e=>{const button=e.target.closest('[data-find-item]');if(!button)return;finder.close();openItem(button.dataset.findItem)};
  finder.addEventListener('keydown',e=>{const buttons=Array.from(finder.querySelectorAll('[data-find-item]'));if(!buttons.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const index=buttons.indexOf(document.activeElement);const next=index<0?(e.key==='ArrowDown'?0:buttons.length-1):(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next].focus()}else if(e.key==='Enter'&&e.target===$('novaFindInput')){e.preventDefault();buttons[0].click()}});
  document.addEventListener('keydown',e=>{if(active()&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showFinder()}});
  // Pointer lighting is decorative; keyboard and touch controls work without it.
  let frame=0,pending=null;
  $('itemGrid').addEventListener('pointermove',e=>{if(!motion()||e.pointerType!=='mouse')return;const card=e.target.closest('.item-card');if(!card)return;pending={card,x:e.clientX,y:e.clientY};if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const p=pending;if(!p?.card.isConnected)return;const r=p.card.getBoundingClientRect();p.card.style.setProperty('--pointer-x',((p.x-r.left)/r.width*100)+'%');p.card.style.setProperty('--pointer-y',((p.y-r.top)/r.height*100)+'%')})});
  new MutationObserver(()=>{if(active())updateFeatured();else if(finder.open)finder.close()}).observe(document.documentElement,{attributes:true,attributeFilter:['data-design']});
})();
